name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup Node
        uses: actions/setup-node@v2.1.1
      - name: Install Dependencies
        run: npm install
      - name: Test Specification
        run: npm run cov
      - name: Report Coverage
        run: npx codecov
